DROP TABLE oltp.staging_airlines;
DROP TABLE oltp.staging_airports;
DROP TABLE oltp.staging_bookings;
DROP TABLE oltp.staging_customers;
DROP TABLE oltp.staging_flights;
DROP TABLE oltp.staging_payments;
DROP TABLE oltp.staging_flight_seats;
DROP TABLE oltp.staging_services;
DROP TABLE oltp.staging_booking_services;